### ISSUE TITLE
/report (aliases) don't work

### ISSUE THREAD

**Issue by enterih** [IzzelAliz/BugRepGUI#1]
Any Changes in the config don't work. No error is displaying

When I use /report the chat say /report

It's reported on Spigot more time. It's nice when u can fix it

**Comment by IzzelAliz** [comment]
Yes, it is fixing.

**Comment by enterih** [comment]
Thanks for the fast update  :)

A new bug is here, that came with your fix:

When player type /report or /bug report or other aliases then he can enter his message. but when he's moving or looking arround the bug report will be finish.

**Comment by IzzelAliz** [comment]
of course. i changed the submit method.
I think this may better
